algorandfoundation/algokit-cli

.github/workflows/cd.yaml

build: force patch bumps on prod builds if no other tags found

---

README.md
src/algokit/cli/init.py
tests/init/test_init.py
tests/init/test_init.test_init_missing_git.approved.txt

fix: improve windows install instructions and fix algokit failing to start if git not present

---

src/algokit/core/doctor.py
src/algokit/core/sandbox.py
tests/doctor/test_doctor.test_doctor_with_docker_compose_version_gitpod.approved.txt
tests/doctor/test_doctor.test_doctor_with_docker_compose_version_unparseable.approved.txt

fix(doctor): Ensuring full docker version information is visible in Doctor output to improve debugging

---

src/algokit/cli/init.py

as per instructions, pressing enter should take you back to the template selection menu

fix: allow going back to template selection from custom url

---

poetry.lock
pyproject.toml
src/algokit/cli/goal.py
src/algokit/cli/init.py
src/algokit/core/sandbox.py
tests/bootstrap/test_bootstrap_env.py
tests/goal/test_goal.py
tests/goal/test_goal.test_goal_console_failed_algod_not_created.approved.txt

When executing goal/bash inside algod container only show localnet hint if it looks like the container doesn't exist or isn't running.
Also update ruff (so that we have pattern matching support).

`goal` / `localnet console` exit code smarts

---

src/algokit/cli/init.py
tests/bootstrap/test_bootstrap_env.test_bootstrap_env_dotenv_different_prompt_scenarios.approved.txt
tests/bootstrap/test_bootstrap_poetry.test_bootstrap_poetry_without_poetry.approved.txt
tests/bootstrap/test_bootstrap_poetry.test_bootstrap_poetry_without_poetry_failed_install.approved.txt
tests/bootstrap/test_bootstrap_poetry.test_bootstrap_poetry_without_poetry_failed_poetry_path.approved.txt
tests/bootstrap/test_bootstrap_poetry.test_bootstrap_poetry_without_poetry_or_pipx_path[no_system_pythons].approved.txt
tests/bootstrap/test_bootstrap_poetry.test_bootstrap_poetry_without_poetry_or_pipx_path[python3_only].approved.txt
tests/bootstrap/test_bootstrap_poetry.test_bootstrap_poetry_without_poetry_or_pipx_path[python_and_python3].approved.txt
tests/bootstrap/test_bootstrap_poetry.test_bootstrap_poetry_without_poetry_or_pipx_path[python_only].approved.txt
tests/bootstrap/test_bootstrap_poetry.test_bootstrap_poetry_without_poetry_or_pipx_path_failed_install.approved.txt
tests/bootstrap/test_bootstrap_poetry.test_bootstrap_poetry_without_poetry_or_pipx_path_failed_poetry_path.approved.txt
tests/bootstrap/test_bootstrap_poetry.test_bootstrap_poetry_without_poetry_or_pipx_path_or_pipx_module.approved.txt
tests/conftest.py
tests/init/test_init.py
tests/init/test_init.test_init_ask_about_git.approved.txt
tests/init/test_init.test_init_bootstrap_no.approved.txt
tests/init/test_init.test_init_bootstrap_yes.approved.txt
tests/init/test_init.test_init_do_not_use_existing_folder.approved.txt
tests/init/test_init.test_init_input_template_url.approved.txt
tests/init/test_init.test_init_minimal_interaction_required_no_git_no_network_no_bootstrap.approved.txt
tests/init/test_init.test_init_minimal_interaction_required_yes_git_no_network.approved.txt
tests/init/test_init.test_init_no_community_template.approved.txt
tests/init/test_init.test_init_no_interaction_required_no_git_no_network_with_vscode.approved.txt
tests/init/test_init.test_init_project_name.approved.txt
tests/init/test_init.test_init_project_name_not_empty.approved.txt
tests/init/test_init.test_init_project_name_reenter_folder_name.approved.txt
tests/init/test_init.test_init_template_selection.approved.txt
tests/init/test_init.test_init_use_existing_folder.approved.txt

Also:
- add playground template to blessed list
- forward questionary output to sys.stdout

Add template descriptions to interactive selection

---

.pre-commit-config.yaml
poetry.lock
pyproject.toml
tests/bootstrap/test_bootstrap.py
tests/bootstrap/test_bootstrap_all.py
tests/bootstrap/test_bootstrap_env.py
tests/bootstrap/test_bootstrap_npm.py
tests/bootstrap/test_bootstrap_poetry.py
tests/completions/test_completions.py
tests/conftest.py
tests/doctor/test_doctor.py
tests/explore/test_explore.py
tests/goal/test_goal.py
tests/init/test_init.py
tests/localnet/test_localnet.py
tests/localnet/test_localnet_console.py
tests/localnet/test_localnet_reset.py
tests/localnet/test_localnet_start.py
tests/localnet/test_localnet_status.py
tests/localnet/test_localnet_stop.py
tests/test_root.py
tests/utils/click_invoker.py
tests/utils/proc_mock.py
tests/version_check/test_version_check.py

enable/run mypy on `tests/`

---

src/algokit/cli/__init__.py
src/algokit/cli/bootstrap.py
src/algokit/cli/init.py
src/algokit/core/questionary_extensions.py

Note that text will still be wrapped to the terminal width if that is less than 120
Style issues fixed:
- remove underscore from public method
- fix imports in init.py
- remove unnecessary import-rename of NoReturn

Increase max terminal width to 120

---

docs/cli/index.md
src/algokit/cli/init.py

As discussed on Slack, this is a beaker starter template. This template is less complex but offers less convenience than the beaker production template. Primary motivation is to offer a template that supports all features of Algokit, including Dappflow, that newer developers can use to start developing a smart contract.

Beaker Starter template

---

.github/pull_request_template.md
docs/architecture-decisions/2022-11-14_sandbox-approach.md
docs/architecture-decisions/2022-11-22_beaker-testing-strategy.md
docs/architecture-decisions/2023-01-11_beaker_productionisation_review.md
docs/architecture-decisions/2023-01-11_brew_install.md
docs/architecture-decisions/2023-01-12_smart-contract-deployment.md

added pr template, fixed last name in architecture decisions

Things i shouldve done before

---

LICENSE

Fixes #241
use a range (a more radical alternative would be to not used the year(s) at all)
see https://github.com/algorandfoundation/algokit-cli/issues/241#issuecomment-1518456944

update copyright year

---

docs/features/localnet.md

mention Hyper-V Docker backend alternative

---

README.md

- Fixing whitespaces glitch in readme

docs: fixing underline caused by whitespace in html tags on readme

---

docs/cli/index.md
src/algokit/cli/init.py

- Whitelisting react and full stack templates

feat: adding react and fullstack templates

---

src/algokit/cli/init.py

- Adding extra checks for whether to open a code-workspace file directly instead of a folder path

feat: detecting code workspace changes

---

docs/tutorials/intro.md

Fixed Typo

---

docs/features/dispenser.md

- Adding documentation on algokit dispense command

docs: adding initial docs on algokit dispense command

---

docs/features/dispenser.md

- Extra docs for dispenser refund command

docs: explicit reference on how to obtain the dispenser address

---

docs/cli/index.md
docs/features/deploy.md
src/algokit/cli/deploy.py
src/algokit/cli/tasks/sign_transaction.py
src/algokit/cli/tasks/vanity_address.py
src/algokit/cli/tasks/wallet.py
tests/deploy/test_deploy.py
tests/deploy/test_deploy.test_deploy_dispenser_alias.deployer.approved.txt
tests/deploy/test_deploy.test_deploy_dispenser_alias.dispenser.approved.txt

- Adding 2 optional params to load dispener/deployer mnemonics from aliases

feat: deploy aliasing support

---

docs/cli/index.md
docs/features/tasks.md
docs/features/tasks/ipfs.md
src/algokit/__init__.py
src/algokit/cli/task.py
src/algokit/cli/tasks/ipfs.py
src/algokit/core/tasks/ipfs.py
tests/tasks/TestIpfsLogin.test_ipfs_login_exists.approved.txt
tests/tasks/TestIpfsLogin.test_ipfs_login_successful.approved.txt
tests/tasks/TestIpfsLogout.test_ipfs_logout.approved.txt
tests/tasks/TestIpfsUpload.test_ipfs_upload_http_error.approved.txt
tests/tasks/TestIpfsUpload.test_ipfs_upload_successful.approved.txt
tests/tasks/test_ipfs.py
tests/tasks/test_sign_transaction.py

- Web3 storage based ipfs upload functionality with progress indicator

feat: ipfs upload

---

src/algokit/cli/tasks/vanity_address.py
src/algokit/core/tasks/vanity_address.py
tests/tasks/test_vanity_address.py
tests/tasks/test_vanity_address.test_vanity_address_on_termination.approved.txt

- Removing pools, using simple processes in an array, supposedly has better termination handling on windows

chore: minor tweaks in vanity address performance

---

docs/features/tasks.md

docs: fixing typo in docs

---

docs/tutorials/intro.md

typo resolved

---

.vscode/extensions.json

chore: Updated deprecated vscode extension

---

src/algokit/core/sandbox.py
tests/localnet/test_localnet_reset.test_localnet_reset_with_existing_sandbox_with_out_of_date_config.approved.txt
tests/localnet/test_localnet_reset.test_localnet_reset_without_existing_sandbox.approved.txt
tests/localnet/test_localnet_start.test_localnet_start.approved.txt
tests/localnet/test_localnet_start.test_localnet_start_health_bad_status.approved.txt
tests/localnet/test_localnet_start.test_localnet_start_health_failure.approved.txt
tests/localnet/test_sandbox.test_get_docker_compose_yml.approved.txt

Hotfix for a typo in conduit compose causing issues on docker running on windows

fix: hotfixing conduit path for localnet windows compatibility

---

docs/cli/index.md
src/algokit/cli/init.py

- Dev preview for puya template

chore: puya template

---

tests/tasks/test_analyze.py

fix: see if this fixes the flakey test

---

src/algokit/cli/common/utils.py
tests/dispenser/TestFundCommand.test_fund_command_from_alias_successful.approved.txt
tests/dispenser/TestFundCommand.test_fund_command_success.False.False.approved.txt
tests/dispenser/TestFundCommand.test_fund_command_success.False.True.approved.txt
tests/dispenser/TestFundCommand.test_fund_command_success.True.False.approved.txt
tests/dispenser/TestFundCommand.test_fund_command_success.True.True.approved.txt
tests/tasks/test_mint.test_mint_token_successful.address.False.testnet.approved.txt
tests/tasks/test_mint.test_mint_token_successful.alias.True.testnet.approved.txt
tests/tasks/test_transfer.test_transfer_on_testnet.approved.txt

Allo isn't planning on supporting testnet at this stage.

chore: update testnet urls

---

.github/workflows/cd.yaml
.github/workflows/publish-release-packages.yaml

- Updating artifacts action to v4

chore: bumping artifact stages to v4

---

.github/workflows/cd.yaml

- hotfixing typo caused by a merge conflict for prior PR

fix: patch cd pipeline merge conflict

---

.vscode/launch.json
CONTRIBUTING.md
debug.py

Fixes #
- Update README to make the requirement for an activated poetry virtual-env clearer.
- Update debug module to run --version command if there is no args.in
- Update VSCode launch to use debugpy

Improve onboarding experience

---

docs/architecture-decisions/2024-01-23_init-wizard-v2.md

Fixes (todo: include link to related minor enhancement spike)
- Outlines a new interactive flow for init wizard experience
- Outlines new proposals around improving management on full-stack templates and generators
- Outlines a new proposal to introduce more refined semantic around `project` command group that can aggregate static (and already project-centric) commands like `deploy`, `bootstrap` and allow defining any amount of extra user specific custom commands.

docs: adr init wizard v2 and related improvements

---

src/algokit/cli/init.py

- Patch to removes branch references for latest blessed templates

fix: remove per branch dependencies on blessed templates

---

.github/workflows/cd.yaml
README.md

- Minor tweak in readme, patching the visitors badge
- Minor tweak in CD pipeline, ignore changes in .vscode, .idea, .md files and docs folder to avoid spamming with algokit releases when there are no user facing changes in-place to release

docs: minor patch in the badge

---

src/algokit/cli/init.py

- Fixes the issue when instantiating the workspace based project causes cli to instantiate git at standalone project level

fix: path resolution to ensure git is initialized at workspace level

---

docs/architecture-decisions/2023-07-19_advanced_generate_command.md

change last name in 2023-07-19_advanced_generate_command.md

---

CONTRIBUTING.md
docs/algokit.md

Dummy commit to request classic confinement access on snapstore, opened to issue a commit with verifiable gpg keys. Do not merge

docs: ref commit for snapcraft

---

docs/architecture-decisions/2024-03-06_local_dev_ui_packaging.md

Local dev UI packaging ADR

---

docs/features/generate.md
tests/compile/test_python.py
tests/init/test_init.py
tests/init/test_init.test_init_wizard_v2_flow.Custom Template.approved.txt
tests/init/test_init.test_init_wizard_v2_flow.DApp Frontend.approved.txt
tests/init/test_init.test_init_wizard_v2_flow.Smart Contract.approved.txt

- Updating tests based on usage of the merged templates
- Action todo comment and revert back to previous test state
- Add some more info about client generator package resolution

docs: few tweaks post release

---

README.md

Adding explicit note on min npm and node versions

docs: minor refinements in npm min version spec

---

poetry.lock
src/algokit/core/sandbox.py
tests/localnet/test_localnet_reset.test_localnet_reset_with_existing_sandbox_with_out_of_date_config.approved.txt
tests/localnet/test_localnet_reset.test_localnet_reset_without_existing_sandbox.approved.txt
tests/localnet/test_localnet_start.test_localnet_start.approved.txt
tests/localnet/test_localnet_start.test_localnet_start_health_bad_status.approved.txt
tests/localnet/test_localnet_start.test_localnet_start_health_failure.approved.txt
tests/localnet/test_localnet_start.test_localnet_start_with_name.approved.txt
tests/localnet/test_sandbox.test_get_docker_compose_yml.approved.txt

fix: remove deprecated version from localnet compose file

---

docs/tutorials/intro.md

Fixes #
- Removes misspelling intro.md tutorial docs

docs: remove spelling mistake in intro.md instalation docs

---

src/algokit/core/sandbox.py
tests/localnet/conftest.py
tests/localnet/test_localnet_reset.test_localnet_reset_with_existing_sandbox_with_out_of_date_config.approved.txt
tests/localnet/test_localnet_reset.test_localnet_reset_with_existing_sandbox_with_up_to_date_config.approved.txt
tests/localnet/test_localnet_reset.test_localnet_reset_without_existing_sandbox.approved.txt
tests/localnet/test_localnet_start.py
tests/localnet/test_localnet_start.test_localnet_img_check_cmd_error.approved.txt
tests/localnet/test_localnet_start.test_localnet_start.approved.txt
tests/localnet/test_localnet_start.test_localnet_start_failure.approved.txt
tests/localnet/test_localnet_start.test_localnet_start_health_bad_status.approved.txt
tests/localnet/test_localnet_start.test_localnet_start_health_failure.approved.txt
tests/localnet/test_localnet_start.test_localnet_start_out_date.approved.txt
tests/localnet/test_localnet_start.test_localnet_start_out_of_date_definition.approved.txt
tests/localnet/test_localnet_start.test_localnet_start_out_of_date_definition_and_missing_config.approved.txt
tests/localnet/test_localnet_start.test_localnet_start_up_to_date_definition.approved.txt
tests/localnet/test_localnet_start.test_localnet_start_with_gitpod_docker_compose_version.approved.txt
tests/localnet/test_localnet_start.test_localnet_start_with_name.approved.txt
tests/localnet/test_localnet_start.test_localnet_start_with_unparseable_docker_compose_version.approved.txt
tests/localnet/test_sandbox.test_algod_network_template_json.approved.txt
tests/localnet/test_sandbox.test_get_docker_compose_yml.approved.txt

- Patches the errored behaviour against latest algod image

fix: remove ConsensusProtocol = future; unpin algod

---

docs/features/config.md
docs/features/project.md
docs/features/project/link.md
docs/features/project/list.md
docs/features/project/run.md

docs: minor revamp in project/config docs

---

tests/init/test_init.py
tests/init/test_init.test_init_with_any_template_url_get_community_warning.approved.txt
tests/init/test_init.test_init_with_any_template_url_get_community_warning_with_unsafe_tag.approved.txt
tests/init/test_init.test_init_with_custom_env.approved.txt
tests/init/test_init.test_init_with_official_template_name.approved.txt

- previous PR merged reported false positives since some templates werent updated to exclude .env.{network_name} files, with those released - extra snapshots need to be updated to reflect new structure

chore: patching tests since previous pr had outdated cache

---

README.md
docs/cli/index.md
docs/features/generate.md
docs/features/init.md
docs/tutorials/algokit-template.md
docs/tutorials/intro.md
src/algokit/cli/init.py
tests/init/test_init.test_init_template_selection.approved.txt
tests/init/test_init.test_init_wizard_v2_flow.Full Stack.approved.txt
tests/init/test_init.test_init_wizard_v2_flow.Smart Contract.approved.txt

- Minor tweaks to deprecate beaker template
- Refreshing outdated docs

chore: deprecating beaker; refreshing outdated docs

---

src/algokit/cli/localnet.py
tests/localnet/test_localnet_reset.test_localnet_reset_with_existing_sandbox_with_out_of_date_config.approved.txt

- Minor patch to change wording when for log message informing on update of the localnet

chore: updating localnet config update log message for --no-update case

---

.github/workflows/publish-release-packages.yaml

Minor patches to address 2.4.0 cd errors

chore: minor patches in cd pipeline

---

.github/workflows/pr.yaml
README.md

Extra notes on snap based installation

docs: more details on snap install in README.md

---

docs/algokit.md
docs/cli/index.md
docs/features/completions.md
docs/features/dispenser.md
docs/features/generate.md
docs/features/localnet.md
docs/features/project.md
docs/features/project/deploy.md
docs/features/tasks/sign.md

Fixes #
- Updated AlgoKit quick start tutorial links
- Updated algokit templates link
- Fixed invalid anchor links
- Fixed typos

docs: updated invalid links and fixed some typos in the docs
