- docs/cli/index.md
- src/algokit/cli/goal.py
- src/algokit/core/proc.py
- tests/goal/test_goal.test_goal_complex_args.approved.txt
- tests/goal/test_goal.test_goal_help.approved.txt
- tests/goal/test_goal.test_goal_no_args.approved.txt
- tests/goal/test_goal.test_goal_simple_args.approved.txt
Fixes #102 
additionally: 
fix: warn rather than ignore extra arguments passed to goal --console
fix: remove unnecessary --no-console flag for goal
> pass through sys.stdin when executing goal command in case it wants input

- scripts/chocolatey/algokit/algokit.nuspec
- scripts/chocolatey/algokit/tools/chocolateyinstall.ps1
- scripts/chocolatey/algokit/tools/chocolateyuninstall.ps1
make git an explicit dependency so 0.1.0 package will work after install
> build: explicitly handle stderr output during chocolatey installation

- docs/cli/index.md
- src/algokit/cli/localnet.py
- src/algokit/core/sandbox.py
- tests/localnet/test_localnet.test_localnet_help.approved.txt
note, no tests - it's just running a simple command. not much of value to test here without actually passing through to docker compose for real
> feat: add a command to see logs from localnet docker containers

- src/algokit/cli/explore.py
- tests/explore/test_explore.test_explore.localnet.approved.txt
If a user is running algokit in gitpod (which we use in bootcamps), running `algokit localnet explore` will fail because dappflow won't be able to connect to `localhost`. This is a minor change that checks whether algokit is running in gitpod and modifies the localnet connection information accordingly. 
End result is `algokit localnet explore` working the same on local machine and on gitpod
> Add Gitpod check for localnet explore

- docs/architecture-decisions/2023-06-06_frontend-templates.md
- fixing header to include deciders (participants of pr review) and status
> docs: fixing header in recently merged adr to reflect status and deciders

- docs/cli/index.md
- src/algokit/cli/init.py
Fixes #
- Updating list to include upcoming templates 
Needs to be merged AFTER:
1. 1.3.0 release
2. support for deploy is merged on beaker template
3. fullstack is updated to point to new templates via -t flag 
4. new template repos are made public
> refactor: updating list of official templates

- poetry.lock
- src/algokit/cli/localnet.py
- src/algokit/core/proc.py
- src/algokit/core/sandbox.py
- tests/localnet/conftest.py
- tests/localnet/test_localnet_reset.py
- tests/localnet/test_localnet_reset.test_localnet_reset_with_existing_sandbox_with_out_of_date_config.approved.txt
- tests/localnet/test_localnet_reset.test_localnet_reset_with_existing_sandbox_with_up_to_date_config.approved.txt
- tests/localnet/test_localnet_start.py
- tests/localnet/test_localnet_start.test_localnet_img_check_cmd_error.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_failure.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_health_bad_status.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_health_failure.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_out_date.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_out_of_date_definition.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_out_of_date_definition_and_missing_config.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_up_to_date_definition.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_with_gitpod_docker_compose_version.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_with_unparseable_docker_compose_version.approved.txt
https://dev.azure.com/MakerXStudio/AlgoKit%20(Algorand%20Foundation)/_workitems/edit/431
> fix: localnet displays a warning when image is out of date

- poetry.lock
- src/algokit/cli/tasks/vanity_address.py
- src/algokit/core/tasks/vanity_address.py
- tests/tasks/test_vanity_address.py
- tests/tasks/test_vanity_address.test_vanity_address_on_termination.approved.txt
- Further testing with Rob on windows revealed performance issues with counter hence pr refactors the main generator function:
- - moving the matcher functions into a global variable with lambdas
- - reducing the rate at which shared counter values are accessed (depending on cpu)
- - adding error handling for keyboard interrupts + test case for confirming the cli output
> refactor: performance improvements for vanity; swifter termination handling

- poetry.lock
- minor bump to address pip-audit warning
> chore: bumping dependency for pip-audit warning fix

- docs/cli/index.md
- docs/features/tasks.md
- docs/features/tasks/sign.md
- src/algokit/cli/common/utils.py
- src/algokit/cli/generate.py
- src/algokit/cli/task.py
- src/algokit/cli/tasks/sign_transaction.py
- src/algokit/cli/tasks/transfer.py
- src/algokit/cli/tasks/utils.py
- src/algokit/cli/tasks/wallet.py
- tests/generate/test_generate_client.test_generate_no_options.approved.txt
- tests/tasks/TestAddAlias.test_wallet_add_invalid_address.approved.txt
- tests/tasks/test_sign_transaction.py
- tests/tasks/test_sign_transaction.test_file_decoding_errors.approved.txt
- tests/tasks/test_sign_transaction.test_mutually_exclusive_options.approved.txt
- tests/tasks/test_sign_transaction.test_sign_atomic_txn_group_successful.approved.txt
- tests/tasks/test_sign_transaction.test_sign_from_stdin_with_address_successful.approved.txt
- tests/tasks/test_sign_transaction.test_sign_from_stdin_with_alias_successful.approved.txt
- tests/tasks/test_sign_transaction.test_sign_many_from_file_with_address_successful.approved.txt
- tests/tasks/test_sign_transaction.test_sign_many_from_file_with_alias_successful.approved.txt
- tests/tasks/test_sign_transaction.test_transaction_decoding_errors.approved.txt
- tests/tasks/test_transfer.py
- This PR refactors the code by moving some functions from transfer.py to utils.py for better code organization and reusability. It also adds a new feature to sign Algorand transactions in sign_transaction.py.
- Adding `.` at the end of all help messages in tasks for consistency. Updating affected tests, regenerating docs
- Acceptance criteria explicitly mentions that this operation allows working with single transaction per file/base64 encoded record passed. @robdmoore just making sure we are on the same page, as you can see in the implementation if user provides a file with more than 1 txn in the file click will raise an exception saying only 1 txn per file is supported for signing
> feat: transaction signing task; polishing tasks

- README.md
- poetry.lock
- Updating docs as an important note to warn users for dependency incompatibility of python 3.12 with installing AlgoKit.
> docs: updating docs for the issue on python 3.12

- poetry.lock
- pyproject.toml
- src/algokit/core/typed_client_generation.py
- upgrading algokit-utils and generator dependency versions
- potential bug fix for ts client generator, certain users reported cached versions of v2.2.2 of ts client generator failing on `Error: Cannot find module 'cross-fetch'`, the proposed changes bump the version in npx invocation to latest (that has dependency on major version bumped algokit-utils-ts) ([discord thread](https://discord.com/channels/491256308461207573/1163926209491644499/1165994950140370995))
> chore: upgrading dependencies on algokit-utils and client generator

- poetry.lock
minor bump to address pip-audit warning
> chore: bumping dependency for pip-audit warning

- src/algokit/core/goal.py
- tests/goal/test_goal.py
- Add support for copying the multiple output files that goal clerk split generates
- Add support for file paths like `./my-file.ext` and `~/my-file.ext`
- Support additional output arguments available in the goal commands
> fix: support the multiple file outputs of goal clerk split

- src/algokit/core/goal.py
Detect goal paths like `~/test.txt` as valid file paths.
> fix: support detect ~/test.txt as valid goal paths

- src/algokit/cli/explore.py
Adds support for GitHub codespaces with algokit explore, similar to how gitpod was supported.
Future work to be done on bootstrap so that it will setup the .env to the proper urls (opposed to localhost) for the frontend.
> Support codespaces for explore

- poetry.lock
- pyproject.toml
- src/algokit/cli/generate.py
Fixes #352
This error started occurring when updating to the latest copier, which also required an update to pydantic. It appears pydantic no longer is ok with passing a List of Tuple, where a dictionary is required.
- Correctly type and convert the `list[tuple[str, str]]` to a `dict[str,str]` which fixes the pydantic error.
> fix: correctly convert list of tuple to dictionary

- .github/workflows/check-python.yaml
Cleaning up temporarily audit ignored dependencies
> chore: Remove audit ignores, as they've all been fixed

- .github/workflows/build-python.yaml
- poetry.lock
- pyproject.toml
- src/algokit/core/sandbox.py
- tests/goal/test_goal.py
- tests/localnet/conftest.py
- tests/localnet/test_localnet_console.py
- tests/localnet/test_localnet_reset.py
- tests/localnet/test_localnet_reset.test_localnet_reset_with_existing_sandbox_with_out_of_date_config.approved.txt
- tests/localnet/test_localnet_reset.test_localnet_reset_with_existing_sandbox_with_up_to_date_config.approved.txt
- tests/localnet/test_localnet_reset.test_localnet_reset_without_existing_sandbox.approved.txt
- tests/localnet/test_localnet_start.py
- tests/localnet/test_localnet_start.test_localnet_img_check_cmd_error.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_failure.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_health_bad_status.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_health_failure.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_out_date.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_out_of_date_definition.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_out_of_date_definition_and_missing_config.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_up_to_date_definition.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_with_gitpod_docker_compose_version.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_with_unparseable_docker_compose_version.approved.txt
- tests/localnet/test_sandbox.py
- tests/localnet/test_sandbox.test_algod_network_template_json.approved.txt
- tests/localnet/test_sandbox.test_get_conduit_yaml.approved.txt
- tests/localnet/test_sandbox.test_get_config_json.approved.txt
- tests/localnet/test_sandbox.test_get_docker_compose_yml.approved.txt
- Adds support and migrates to -> official indexer v3 image (latest tag as of today)
- Adds required dependency on conduit which forces using extra algod follower container that does slow down execution of certain operations as well as boot up and shut down time of compose environment
- Adding pytest-xdist to speed up test execution
> feat: migrating localnet to latest indexer v3.x images

- .github/workflows/build-python.yaml
- .github/workflows/check-python.yaml
- .pre-commit-config.yaml
- .vscode/settings.json
- CONTRIBUTING.md
- debug.py
- poetry.lock
- pyproject.toml
- src/algokit/__init__.py
- src/algokit/cli/deploy.py
- src/algokit/cli/tasks/mint.py
- src/algokit/core/log_handlers.py
- src/algokit/core/proc.py
- src/algokit/core/tasks/vanity_address.py
- src/algokit/core/version_prompt.py
- tests/init/test_init.py
- tests/localnet/conftest.py
- tests/localnet/test_localnet_reset.py
- tests/localnet/test_localnet_start.py
- tests/tasks/test_send_transaction.py
- tests/tasks/test_wallet.py
- tests/utils/proc_mock.py
Fixes #
- updating vscode setting as formatting/linting have been deprecated in favour of dedicated extensions
- working with ruff formatter instead of black
> chore: ruff improvements

- poetry.lock
- pyproject.toml
Fixes
`Unhandled MulticodecValueError: Invalid multicodec status 'deprecated'.` that is being reported on discord.
> fix: update multiformats version as it needs to be in sync with multiformats-config

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- Adding issue templates that are already present on utilts-ts, should make it easier for us to resolve customer issues faster, given that we almost always need info like algokit doctor ouput and etc
> chore: adding github issue templates

- .github/workflows/build-python.yaml
- CONTRIBUTING.md
- src/algokit/cli/tasks/analyze.py
- src/algokit/core/tasks/analyze.py
- tests/tasks/test_analyze.py
- tests/tasks/test_analyze.test_analyze_abort_disclaimer.approved.txt
- tests/tasks/test_analyze.test_analyze_diff_flag.approved.txt
- tests/tasks/test_analyze.test_analyze_diff_flag_missing_old_report.approved.txt
- tests/tasks/test_analyze.test_analyze_error_in_tealer.approved.txt
- tests/tasks/test_analyze.test_analyze_error_no_pipx.approved.txt
- tests/tasks/test_analyze.test_analyze_multiple_files.approved.txt
- tests/tasks/test_analyze.test_analyze_multiple_files_recursive.approved.txt
- tests/tasks/test_analyze.test_analyze_single_file.approved.txt
- tests/tasks/test_analyze.test_analyze_skipping_tmpl_vars.approved.txt
- tests/tasks/test_analyze.test_exclude_vulnerabilities.approved.txt
- Fixes compatibility with windows and aligns installation process for tealer to match the approach with poetry installation in bootstrap 
- since pytest is run via `pytest-xdist` in order to avoid race conditions on initial install of tealer, contributing docs and pipeline are updated to install tealer prior to execution of the pytest suite.
> fix: installation process for tealer (windows compatibility)

- .github/actions/setup-poetry/action.yaml
- .github/workflows/build-binaries.yaml
- .github/workflows/build-python.yaml
- .github/workflows/cd.yaml
- .github/workflows/check-python.yaml
- CONTRIBUTING.md
- src/algokit/core/tasks/analyze.py
- tests/tasks/test_analyze.test_analyze_abort_disclaimer.approved.txt
- tests/tasks/test_analyze.test_analyze_diff_flag.approved.txt
- tests/tasks/test_analyze.test_analyze_diff_flag_missing_old_report.approved.txt
- tests/tasks/test_analyze.test_analyze_error_in_tealer.approved.txt
- tests/tasks/test_analyze.test_analyze_multiple_files.approved.txt
- tests/tasks/test_analyze.test_analyze_multiple_files_recursive.approved.txt
- tests/tasks/test_analyze.test_analyze_single_file.approved.txt
- tests/tasks/test_analyze.test_analyze_skipping_tmpl_vars.approved.txt
- tests/tasks/test_analyze.test_exclude_vulnerabilities.approved.txt
Fixes https://github.com/algorandfoundation/algokit-cli/issues/414
- Pinning tealer to fixed official version served from pypi 
- Extra minor improvements in `cache` step that takes patch version into account.
> chore: pinning tealer to 3.12 compatible version from pypi

- .github/actions/build-binaries/action.yaml
- .github/actions/setup-poetry/action.yaml
- .github/workflows/build-binaries.yaml
- .github/workflows/build-python.yaml
- .github/workflows/cd.yaml
Fixes #389 
- Include the process architecture into the output binary.
- Install `poetry` directly with `pip`.
- Build an extra binary for Apple Silicon.
> chore: build binary for Apple Silicon

- .github/workflows/build-binaries.yaml
Codespaces are still running Ubuntu 20.04 and failing to run the new binaries. This pins the *nix builds to 20.04 which should be forwards compatible with GLIBC. On a unrelated note, the binaries are working great so far everywhere elese! Great work, really excited for them!
```
npx algokit
[10828] Error loading Python lib '/workspaces/algokit-nestjs-template/node_modules/@algokit/cli/bin/_internal/libpython3.12.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /workspaces/algokit-nestjs-template/node_modules/@algokit/cli/bin/_internal/libpython3.12.so.1.0)
```
I started messing around with wrapping the binaries in a light wrapper in `nodejs` and creating a very basic PoC with a template. The template works in CodeSpaces using my cli fork pinned …
> build: pin to ubuntu 20.04 for better compatibility

- src/algokit/core/goal.py
- tests/goal/test_goal.py
- tests/goal/test_goal.test_goal_simple_args_with_input_output_files_with_dot_convention_name.approved.txt
Fixes #423 
- Add support for filenames including dots when using `goal` command.
> fix: fix issue of goal command interacting with filename containing dot

- src/algokit/core/sandbox.py
- src/algokit/core/utils.py
- tests/localnet/test_localnet_reset.test_localnet_reset_with_existing_sandbox_with_out_of_date_config.approved.txt
- tests/localnet/test_localnet_reset.test_localnet_reset_without_existing_sandbox.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_health_bad_status.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_health_failure.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_with_name.approved.txt
- tests/localnet/test_sandbox.test_get_docker_compose_yml.approved.txt
Refined implementation of the contribution from https://github.com/algorandfoundation/algokit-cli/pull/434
- Sets init: true under algod container to ensure graceful shutdown of both instances of algod running inside single container. 
Benchmark of the command with and without init in algod, adding it to other containers is not needed as it's specifically and issue in algod container. 
| Metric      | localnet stop without init    |  localnet stop with init    |
|-------------|----------|----------|
| Time (abs)  | 15.259 s | 5.253 s  |
| User Time   | 0.538 s  | 0.531 s  |
| System Time | 0.178 s  | 0.169 s  |
Containers tested locally against utils and generators, no side effects found affecting tests.
> fix: algod container proper SIGTERM handling

- docs/features/localnet.md
Fixes #443
- Updating docs to provide detailed information on the storage location of configuration files for named LocalNet instances.
> docs: update named localnet documents on config file locations

- docs/features/localnet.md
- Minor typo patches in outdated localnet docs section
> docs: updating dockerhub links on localnet docs

- src/algokit/core/sandbox.py
- tests/localnet/test_localnet_reset.test_localnet_reset_with_existing_sandbox_with_out_of_date_config.approved.txt
- tests/localnet/test_sandbox.test_get_config_json.approved.txt
This is useful when testing.
For example, the algokit-subscriber-ts library needs to go back to block 1 and once you've been running localnet for a while and get past 1000 blocks this test now fails.
This wasn't the previous behaviour (not being archival), but I believe [this change](https://github.com/algorand/go-algorand/releases/tag/v3.22.0-stable) may have caused a change (although it's weird we had `Archival: false` and it was an archival node previously.
> feat: LocalNet should run as an archival node so that you can access all blocks

- .github/dependabot.yml
- poetry.lock
- pyproject.toml
- src/algokit/cli/init.py
- src/algokit/core/generate.py
- src/algokit/core/init.py
This initially started as an attempt to fix the pkgutil.ImpImporter issue reported by @joe-p , however dissecting the lockfiles for versions v1.11.4 (anything from that version or lower does not throw the impimporter error) vs any version starting from v1.12.x (that throws the impimporter runtime error) -> it became very non trivial and took many hours to investigate. Unfortunately updating the lockfile and removing the redundant transient dependency to fix old copier issues was not enough to address the impImporter and the actual root cause there seems to be related to either pip or pipx itself (for reference, latest pip v24 came out 2 weeks ago and utils-py had no pipelines run from main for a month so its entirely possible this impimporter issue has been there for a weeks). 
On the …
> chore: lockfile maintenance; bumping copier version; setting up dependabot

- poetry.lock
Updating to the latest `algokit-utils` to fix #497
This PR in utils fixes the issue https://github.com/algorandfoundation/algokit-utils-py/pull/86
Additionally running a dependency update.
> fix: task transfer on rekeyed account and update dependencies

- src/algokit/__main__.py
- src/algokit/core/utils.py
The animate method in cli was causing unicode errors on windows similar to bug with writes in separate repo that were recently fixed in https://github.com/algorandfoundation/algokit-client-generator-py/pull/27. Adding a check to ensure utf-8 is used
> fix: ensure utf-8 is used as part of cli animate method invocation (windows compatibility)

- poetry.lock
- src/algokit/core/sandbox.py
- tests/goal/test_goal.py
- tests/localnet/test_localnet_console.py
- tests/localnet/test_localnet_reset.py
- tests/localnet/test_localnet_reset.test_localnet_reset_with_existing_sandbox_with_out_of_date_config.approved.txt
- tests/localnet/test_localnet_reset.test_localnet_reset_without_existing_sandbox.approved.txt
- tests/localnet/test_localnet_start.py
- tests/localnet/test_localnet_start.test_localnet_start.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_health_bad_status.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_health_failure.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_with_name.approved.txt
- tests/localnet/test_sandbox.py
- tests/localnet/test_sandbox.test_get_docker_compose_yml.approved.txt
- tests/localnet/test_sandbox.test_proxy_config.approved.txt
Google Chrome is slowly introducing more restrictions on sites which make calls to private network resources.
See https://developer.chrome.com/blog/private-network-access-preflight
This impacts tools like Dappflow.
This PR adds a proxy container to LocalNet and attaches the correct headers to ensure the pre flight CORS request that Chrome sends will succeed.
This PR fixes #524
> fix: add localnet proxy to add Access-Control-Allow-Private-Network header

- src/algokit/core/sandbox.py
- tests/localnet/test_localnet_reset.test_localnet_reset_with_existing_sandbox_with_out_of_date_config.approved.txt
- tests/localnet/test_localnet_reset.test_localnet_reset_without_existing_sandbox.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_health_bad_status.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_health_failure.approved.txt
- tests/localnet/test_localnet_start.test_localnet_start_with_name.approved.txt
- tests/localnet/test_sandbox.test_get_docker_compose_yml.approved.txt
- tests/localnet/test_sandbox.test_proxy_config.approved.txt
A couple of config tweaks to fix some small things I noticed:
- When using the long poll `/v2/status/wait-for-block-after/{round}` endpoint the NGINX proxy upstream timeout can end before the server has responded. The timeout has been increased to ensure that won't happen.
- Sometimes a 502 was returned when calling KMD. Setting the port in the docker compose file fixes this. Both indexer and algod endpoints are fine.
- Tuned config to ensure connections are kept alive.
> fix: some localnet proxy tweaks

- src/algokit/core/tasks/mint/models.py
When minting an asset, null values were being added to the asset metadata and should be filtered out.
> fix: filter null values from asset metadata

- src/algokit/core/sandbox.py
- tests/localnet/test_sandbox.test_proxy_config.approved.txt
Setting `client_max_body_size 0` prevents nginx from returning any 413 error responses.
> chore: disable any max body size limits in the localnet proxy

- README.md
- Troubleshooting guide tweaks to include more details on the error reported by Bruno, in regards to python installation on debian 12 vms having problems with ssl
> docs: extra notes on edge case with python installation on debian

- src/algokit/cli/explore.py
Adds support for exploring localnet in lora launched from a GitHub codespace or GitPod.
Depends on https://github.com/algorandfoundation/algokit-lora/pull/159
> chore: support exploring via lora when running inside a codespace

- .github/workflows/build-binaries.yaml
- .github/workflows/cd.yaml
- scripts/winget/build-installer.ps1
- scripts/winget/installer/priconfig.xml
When building the binaries we were building based on the old version metadata.
This PR fetches the code based on the release tag ref, so that we always build with the correct metadata, as `actions/checkout` will fetch based on the commit hash which triggered the build (not using the main ref), when no ref is supplied.
> fix: build binaries with the correct version information

- src/algokit/cli/explore.py
- src/algokit/core/utils.py
- tests/explore/test_explore.py
- A warning to instruct on how to use explore command within wsl - to be removed once the following is addressed https://github.com/python/cpython/issues/89752. Reported by @CiottiGiorgio
> fix: add warning for cases when explore is used within wsl

- .github/actions/build-binaries/macos/action.yaml
- .github/actions/install-apple-dev-id-cert/action.yaml
- .github/workflows/build-binaries.yaml
- .github/workflows/publish-release-packages.yaml
- entitlements.xml
- pyproject.toml
- scripts/update-brew-cask.sh
- Codesign and notarise the Mac binaries
- Required repository secrets:
- Required repository variables:
- Fixes #389 
- Do not merge this PR until the Apple Developer ID certificate has been created.
> feat:  native binary distribution via homebrew

- poetry.lock
- pyproject.toml
Hotfix for missing requests dependency (caused by removal of auth0). Requests were part of transitive dependencies in a lockfile so installs in CI passed but a fresh install from a pure wheel was failing.
> fix: explicitly pinning requests dependency

- .github/workflows/cd.yaml
- .github/workflows/publish-release-packages.yaml
- scripts/update-brew-cask.sh
Fixing typo in env var secret for accessing the gh app for authentication in brew deploy script (previous approach with PAT is no longer viable and deprecated since mid august)
> chore: minor patches in brew release pipeline

- .github/workflows/build-python.yaml
- poetry.lock
- pyproject.toml
- tests/project/run/test_run.py
Fixes 3.13 compatibility issues reported in https://discord.com/channels/491256308461207573/1293070540172689460/1293075251114278943
- Relaxing constraints to support 3.13
- Adding 3.13 runners to tests matrix
> chore: adding 3.13 to build runners; relaxing constraints

- docs/cli/index.md
- docs/features/goal.md
- src/algokit/cli/goal.py
- tests/goal/test_goal.test_goal_help.approved.txt
- Fixes https://github.com/algorandfoundation/algokit-cli/issues/590
- Fixes edge cases for executing interactive goal commands that may error out on invalid ioctl device
> fix: edge cases for running interactive goal commands with --tty flag

- docs/features/tasks/wallet.md
> docs: add info about keyring in wsl2

- .github/actions/build-binaries/macos/action.yaml
- .github/actions/build-binaries/windows/action.yaml
- .github/workflows/build-binaries.yaml
- pyproject.toml
- scripts/package_mac.sh
The main gist is to further refine access to secrets to ensure none are accessed on PR triggers. Codesigning shall only run on production releases on main branch OR cron triggered checks performed weekly (8am UTC mondays) on main branch. 
- Add a new "with_codesign" parameter to macOS and Windows build actions to control whether binaries should be signed.
- Update the build-binaries workflow to determine code-signing eligibility (via a new "signing" step) based on branch, PR status, and release conditions.
- Update the macOS composite action to set "APPLE_CERT_ID" and "APPLE_BUNDLE_ID" conditionally, falling back to a beta bundle ID when "production_release" is false.
- Replace references to "production_release" in the Windows build action with "with_codesign" for consistency.
- Modify …
> chore: adding conditional to skip codesigning on PR triggers when building binaries

- docs/cli/index.md
- docs/features/project/bootstrap.md
- src/algokit/cli/project/bootstrap.py
- src/algokit/core/project/bootstrap.py
- tests/project/bootstrap/test_bootstrap_all.py
- tests/project/bootstrap/test_bootstrap_npm.py
- tests/project/bootstrap/test_bootstrap_npm.test_bootstrap_npm_ci_mode_with_lock_file[linux].approved.txt
- tests/project/bootstrap/test_bootstrap_npm.test_bootstrap_npm_ci_mode_with_lock_file[macOS].approved.txt
- tests/project/bootstrap/test_bootstrap_npm.test_bootstrap_npm_ci_mode_with_lock_file[windows].approved.txt
- tests/project/bootstrap/test_bootstrap_npm.test_bootstrap_npm_ci_mode_without_lock_file[linux].approved.txt
- tests/project/bootstrap/test_bootstrap_npm.test_bootstrap_npm_ci_mode_without_lock_file[macOS].approved.txt
- tests/project/bootstrap/test_bootstrap_npm.test_bootstrap_npm_ci_mode_without_lock_file[windows].approved.txt
- Adds extra param to npm sub command in `bootstrap` group to run `npm ci` when CI is present as env var and set to true or passed via `--ci` flag (or `--non-interactive/--ci` in `all` command)
- If package lock is not present during npm ci execution it will present and error.
> feat: npm runs `ci` instead on `install` when CI flag is present or passed explicitly`

- docs/cli/index.md
- src/algokit/cli/init.py
- tests/init/test_init.py
This PR addresses:
- Orphan `BEAKER` enum item in `TemplateKey` after the Beaker default template deprecation.
- The AlgoKit CLI side of the Beaker playground template deprecation.
Companion PR: algorandfoundation/algokit-beaker-playground-template#14
> Beaker Full Deprecation

- src/algokit/cli/dispenser.py
- src/algokit/cli/project/link.py
- src/algokit/cli/tasks/analyze.py
- src/algokit/cli/tasks/mint.py
- src/algokit/cli/tasks/vanity_address.py
- src/algokit/core/init.py
- src/algokit/core/proc.py
- src/algokit/core/tasks/analyze.py
- src/algokit/core/tasks/mint/models.py
- tests/init/test_init.py
- tests/project/link/test_link.test_link_command_all_success.approved.txt
- tests/project/link/test_link.test_link_command_by_name_success.approved.txt
- tests/project/link/test_link.test_link_command_multiple_names_no_specs_success.approved.txt
- tests/project/link/test_link.test_link_command_multiple_names_success.approved.txt
Fixes https://github.com/algorandfoundation/algokit-client-generator-ts/issues/154
By forcing the `Popen` used in `run` to use utf-8 encoding we can bypass Windows using the default cp1252 encoding, which causes strange issues.
Additionally I have update a few other places to force utf-8 encoding.
After merging (before release), I'll do some additional smoke tests of the various code paths.
> fix: resolve project run issue by forcing utf-8 encoding on windows

- src/algokit/core/compilers/typescript.py
- src/algokit/core/typed_client_generation.py
When running `algokit compile ts ...` on a project where you have `puya-ts` in the package.json, however it's not actually installed, we incorrectly assume that it's installed and run npx causing the command to hang.
In this scenario you must first install (or bootstrap) the packages, and should throw instead.
> fix: compile ts hangs when puya-ts is detected but not installed in the project

- .github/workflows/build-binaries.yaml
Bumped the ubuntu os version in the build_binaries workflow to 22.04 since 20.04 is being deprecated.
> chore: bumped ubunto build binary version

- .github/workflows/check-python.yaml
- poetry.lock
- pyproject.toml
- src/algokit/core/_vendor/auth0/authentication/token_verifier.py
Resolves the audit issues against the `cryptography` package.
The Auth0 package has relaxed their version constraints in https://github.com/auth0/auth0-python/pull/660, which indicates that the latest version is compatible with the latest `cryptography` and `pyjwt` packages. I diffed the latest version of the Auth0 `token_verifier.py` against the copy we have vendored and nothing meaningful has changed.
Additionally I have tested the dispenser features to confirm everything functions correctly.
> chore: fix audit issue

- src/algokit/core/config_commands/js_package_manager.py
- src/algokit/core/config_commands/py_package_manager.py
- tests/config/test_package_managers.py
- tests/utils/app_dir_mock.py
Previously the tests would write to the user config dir, which meant it would impact bootstrap behaviour on the machine the test was run on.
> chore: ensure bootstrap tests only write config to temp dir
